name: Build, test, and save JAR Artifacts

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build-test-save:
    name: Build, test, and save JAR artifacts
    runs-on: ubuntu-latest

    steps:
    # Checkout
    - name: Checkout Code
      uses: actions/checkout@v3
      
    # Debug: List Directory Structure
    - name: List Repository Contents - DEBUG
      run: ls -R

    # Set up Java 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # User service
    - name: Build and test User service
      run: |
        chmod +x ./gradlew
        ./gradlew build
        ./gradlew test
        ls build/libs
      working-directory: ./user-service
      
    - name: Upload User service artifacts
      uses: actions/upload-artifact@v4
      with:
        name: user-service
        path: user-service/build/libs/*.jar
        
    # Car service
    - name: Build and test Car service
      run: |
        chmod +x ./gradlew
        ./gradlew build
        ./gradlew test
        ls build/libs
      working-directory: ./car-service

    - name: Upload Car service JAR
      uses: actions/upload-artifact@v4
      with:
        name: car-service
        path: car-service/build/libs/*.jar

    # Notification service
    - name: Build and Test Notification service
      run: |
        chmod +x ./gradlew
        ./gradlew build
        ./gradlew test
        ls build/libs
      working-directory: ./notification_service

    - name: Upload Notification service JAR
      uses: actions/upload-artifact@v4
      with:
        name: notification-service
        path: notification_service/build/libs/*.jar
        
    # Add Snyk CLI
    - name: Install Snyk
      run: npm install -g snyk

    # Authenticate Snyk
    - name: Authenticate Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN

    # Run Snyk
    - name: Run Snyk
      run: snyk test --all-projects --severity-threshold=high --sarif-file-output=snyk.sarif
      continue-on-error: true
    
    # Upload Snyk results to github security
    #- name: Upload results to Github code
    #  uses: github/codeql-action/upload-sarif@v3
    #  with:
    #    sarif_file: snyk.sarif

    # Monitor to Snyk Dashboard
    - name: Monitor Project on Snyk
      run: snyk monitor --all-projects
